// AUTO-GENERATED — do not edit by hand. Regenerate: node scripts/heroscape/gen-classic-cards.mjs
// Staged classic cards (base stats only): power:'wip' (no special implemented), no behaviour flags,
// NOT in HS_DRAFT_POOL (undraftable until art lands). baseSize defaults to 1 (fix from the figure image);
// world is '' (DB lacks it). Source: roster.json (HeroScape Card Manager DB, v01/2026).
import type { HSCardDef } from './types';

export const GENERATED_CLASSIC_CARDS: Record<string, HSCardDef> = {
  '10th_regiment_of_foot': { id: '10th_regiment_of_foot', name: '10th Regiment of Foot', shortName: '10th Regiment of Foot', type: 'squad', figures: 4, life: 1, move: 5, range: 6, attack: 2, defense: 2, height: 5, points: 75, letter: '1', species: 'Human', unitClass: 'Soldiers', common: true, power: 'wip' },
  '4th_massachusetts_line': { id: '4th_massachusetts_line', name: '4TH MASSACHUSETTS LINE', shortName: '4TH MASSACHUSETTS LINE', type: 'squad', figures: 4, life: 1, move: 5, range: 6, attack: 2, defense: 2, height: 5, points: 70, letter: '4', species: 'Human', unitClass: 'Soldiers', common: true, power: 'wip' },
  'acolarh': { id: 'acolarh', name: 'Acolarh', shortName: 'Acolarh', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 3, defense: 2, height: 5, points: 110, letter: 'A', species: 'Elf', unitClass: 'Wizard', power: 'wip' },
  'agent_skahen': { id: 'agent_skahen', name: 'AGENT SKAHEN', shortName: 'AGENT SKAHEN', type: 'hero', figures: 1, life: 3, move: 6, range: 7, attack: 3, defense: 3, height: 4, points: 120, letter: 'A', species: 'Human', unitClass: 'Agent', power: 'wip' },
  'alastair_macdirk': { id: 'alastair_macdirk', name: 'Alastair MacDirk', shortName: 'Alastair MacDirk', type: 'hero', figures: 1, life: 6, move: 5, range: 1, attack: 5, defense: 3, height: 5, points: 110, letter: 'A', species: 'Human', unitClass: 'Champion', power: 'wip' },
  'anubian_wolves': { id: 'anubian_wolves', name: 'Anubian Wolves', shortName: 'Anubian Wolves', type: 'squad', figures: 3, life: 1, move: 6, range: 1, attack: 1, defense: 4, height: 5, points: 75, letter: 'A', species: '', unitClass: 'Wolves', common: true, power: 'wip' },
  'arkmer': { id: 'arkmer', name: 'Arkmer', shortName: 'Arkmer', type: 'hero', figures: 1, life: 3, move: 5, range: 5, attack: 4, defense: 2, height: 5, points: 50, letter: 'A', species: 'Elf', unitClass: 'Wizard', power: 'wip' },
  'armoc_vipers': { id: 'armoc_vipers', name: 'Armoc Vipers', shortName: 'Armoc Vipers', type: 'squad', figures: 3, life: 1, move: 7, range: 1, attack: 3, defense: 3, height: 5, points: 65, letter: 'A', species: '', unitClass: 'Viper', common: true, power: 'wip' },
  'ashigaru_harquebus': { id: 'ashigaru_harquebus', name: 'Ashigaru Harquebus', shortName: 'Ashigaru Harquebus', type: 'squad', figures: 4, life: 1, move: 5, range: 6, attack: 2, defense: 1, height: 5, points: 60, letter: 'A', species: 'Human', unitClass: 'Ashigaru', common: true, power: 'wip' },
  'ashigaru_yari': { id: 'ashigaru_yari', name: 'Ashigaru Yari', shortName: 'Ashigaru Yari', type: 'squad', figures: 4, life: 1, move: 5, range: 1, attack: 2, defense: 1, height: 5, points: 40, letter: 'A', species: 'Human', unitClass: 'Ashigaru', common: true, power: 'wip' },
  'atlaga_the_kyrie_warrior': { id: 'atlaga_the_kyrie_warrior', name: 'Atlaga the Kyrie Warrior', shortName: 'Atlaga', type: 'hero', figures: 1, life: 4, move: 5, range: 5, attack: 4, defense: 3, height: 6, points: 90, letter: 'A', species: 'Kyrie', unitClass: 'Warrior', power: 'wip' },
  'aubrien_archers': { id: 'aubrien_archers', name: 'Aubrien Archers', shortName: 'Aubrien Archers', type: 'squad', figures: 3, life: 1, move: 5, range: 6, attack: 2, defense: 2, height: 4, points: 70, letter: 'A', species: 'Elf', unitClass: 'Archers', common: true, power: 'wip' },
  'blastatrons': { id: 'blastatrons', name: 'Blastatrons', shortName: 'Blastatrons', type: 'squad', figures: 4, life: 1, move: 5, range: 7, attack: 1, defense: 2, height: 4, points: 60, letter: 'B', species: 'Soulborg', unitClass: 'Guards', common: true, power: 'wip' },
  'brave_arrow': { id: 'brave_arrow', name: 'Brave Arrow', shortName: 'Brave Arrow', type: 'hero', figures: 1, life: 4, move: 5, range: 1, attack: 4, defense: 3, height: 5, points: 50, letter: 'B', species: 'Human', unitClass: 'Tribesman', power: 'wip' },
  'brunak': { id: 'brunak', name: 'Brunak', shortName: 'Brunak', type: 'hero', figures: 1, life: 3, move: 6, range: 1, attack: 4, defense: 7, height: 8, size: 'huge', baseSize: 2, points: 110, letter: 'B', species: 'Troll', unitClass: 'Troll', power: 'wip' },
  'capuan_gladiators': { id: 'capuan_gladiators', name: 'Capuan Gladiators', shortName: 'Capuan Gladiators', type: 'squad', figures: 3, life: 1, move: 5, range: 1, attack: 3, defense: 3, height: 5, points: 70, letter: 'C', species: 'Human', unitClass: 'Gladiator', common: true, power: 'wip' },
  'chardris': { id: 'chardris', name: 'Chardris', shortName: 'Chardris', type: 'hero', figures: 1, life: 6, move: 5, range: 1, attack: 3, defense: 2, height: 5, points: 90, letter: 'C', species: 'Elf', unitClass: 'Wizard', power: 'wip' },
  'charos': { id: 'charos', name: 'Charos', shortName: 'Charos', type: 'hero', figures: 1, life: 9, move: 5, range: 1, attack: 5, defense: 5, height: 9, size: 'huge', points: 210, letter: 'C', species: 'Dragon', unitClass: 'Dragon', power: 'wip' },
  'concan_the_kyrie_warrior': { id: 'concan_the_kyrie_warrior', name: 'Concan the Kyrie Warrior', shortName: 'Concan', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 4, defense: 4, height: 5, points: 80, letter: 'C', species: 'Kyrie', unitClass: 'Warrior', power: 'wip' },
  'crixus': { id: 'crixus', name: 'Crixus', shortName: 'Crixus', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 5, defense: 3, height: 4, points: 90, letter: 'C', species: 'Human', unitClass: 'Gladiator', power: 'wip' },
  'cyprien_esenwein': { id: 'cyprien_esenwein', name: 'Cyprien Esenwein', shortName: 'Cyprien Esenwein', type: 'hero', figures: 1, life: 6, move: 8, range: 1, attack: 3, defense: 4, height: 4, points: 150, letter: 'C', species: 'Undead', unitClass: 'Lord', power: 'wip' },
  'deadeye_dan': { id: 'deadeye_dan', name: 'DEADEYE DAN', shortName: 'DEADEYE DAN', type: 'hero', figures: 1, life: 3, move: 5, range: 10, attack: 1, defense: 2, height: 5, points: 60, letter: 'D', species: 'Human', unitClass: 'Sniper', power: 'wip' },
  'deathstalkers': { id: 'deathstalkers', name: 'Deathstalkers', shortName: 'Deathstalkers', type: 'squad', figures: 3, life: 1, move: 7, range: 1, attack: 3, defense: 5, height: 5, size: 'large', points: 100, letter: 'D', species: 'Soulborg', unitClass: 'Deathstalkers', common: true, power: 'wip' },
  'deathwalker_7000': { id: 'deathwalker_7000', name: 'Deathwalker 7000', shortName: 'Deathwalker 7000', type: 'hero', figures: 1, life: 1, move: 6, range: 1, attack: 3, defense: 7, height: 5, points: 100, letter: 'D', species: 'Soulborg', unitClass: 'Deathwalker', power: 'wip' },
  'deathwalker_8000': { id: 'deathwalker_8000', name: 'Deathwalker 8000', shortName: 'Deathwalker 8000', type: 'hero', figures: 1, life: 1, move: 5, range: 7, attack: 3, defense: 8, height: 7, size: 'large', points: 130, letter: 'D', species: 'Soulborg', unitClass: 'Deathwalker', power: 'wip' },
  'dumutef_guard': { id: 'dumutef_guard', name: 'Dumutef Guard', shortName: 'Dumutef Guard', type: 'hero', figures: 1, life: 1, move: 6, range: 1, attack: 4, defense: 4, height: 7, size: 'large', points: 25, letter: 'D', species: 'Fiantooth', unitClass: 'Guard', common: true, power: 'wip' },
  'dund': { id: 'dund', name: 'Dünd', shortName: 'Dünd', type: 'hero', figures: 1, life: 4, move: 6, range: 1, attack: 3, defense: 5, height: 4, size: 'large', points: 110, letter: 'D', species: '', unitClass: 'Hunter', power: 'wip' },
  'dzu_teh': { id: 'dzu_teh', name: 'Dzu-Teh', shortName: 'Dzu-Teh', type: 'squad', figures: 3, life: 1, move: 5, range: 1, attack: 4, defense: 3, height: 6, points: 75, letter: 'D', species: 'Wild', unitClass: 'Hunters', common: true, power: 'wip' },
  'elite_onyx_vipers': { id: 'elite_onyx_vipers', name: 'Elite Onyx Vipers', shortName: 'Elite Onyx Vipers', type: 'squad', figures: 3, life: 1, move: 7, range: 1, attack: 3, defense: 2, height: 5, points: 100, letter: 'E', species: '', unitClass: 'Vipers', power: 'wip' },
  'emirroon': { id: 'emirroon', name: 'EMIRROON', shortName: 'EMIRROON', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 3, defense: 3, height: 5, points: 80, letter: 'E', species: 'Elf', unitClass: 'Wizard', power: 'wip' },
  'empress_kiova': { id: 'empress_kiova', name: 'Empress Kiova', shortName: 'Empress Kiova', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 3, defense: 4, height: 6, points: 90, letter: 'E', species: 'Kyrie', unitClass: 'Warrior', power: 'wip' },
  'fyorlag_spiders': { id: 'fyorlag_spiders', name: 'Fyorlag Spiders', shortName: 'Fyorlag Spiders', type: 'squad', figures: 3, life: 1, move: 7, range: 1, attack: 2, defense: 2, height: 2, size: 'small', points: 40, letter: 'F', species: 'Wild', unitClass: 'Arachnids', common: true, power: 'wip' },
  'gladiatrons': { id: 'gladiatrons', name: 'Gladiatrons', shortName: 'Gladiatrons', type: 'squad', figures: 4, life: 1, move: 5, range: 1, attack: 2, defense: 3, height: 5, points: 80, letter: 'G', species: 'Soulborg', unitClass: 'Hunters', common: true, power: 'wip' },
  'gorillinators': { id: 'gorillinators', name: 'Gorillinators', shortName: 'Gorillinators', type: 'squad', figures: 3, life: 1, move: 7, range: 6, attack: 2, defense: 1, height: 5, points: 90, letter: 'G', species: 'Primadon', unitClass: 'Agent', common: true, power: 'wip' },
  'granite_guardians': { id: 'granite_guardians', name: 'Granite Guardians', shortName: 'Granite Guardians', type: 'squad', figures: 3, life: 1, move: 3, range: 1, attack: 3, defense: 5, height: 5, points: 100, letter: 'G', species: 'Elementars', unitClass: 'Guards', common: true, power: 'wip' },
  'grok_riders': { id: 'grok_riders', name: 'Grok Riders', shortName: 'Grok Riders', type: 'squad', figures: 3, life: 1, move: 7, range: 1, attack: 3, defense: 3, height: 5, size: 'large', points: 130, letter: 'G', species: 'Marro', unitClass: 'Marro', common: true, power: 'wip' },
  'guilty_mccreech': { id: 'guilty_mccreech', name: 'Guilty McCreech', shortName: 'Guilty McCreech', type: 'hero', figures: 1, life: 2, move: 5, range: 4, attack: 2, defense: 2, height: 4, points: 30, letter: 'G', species: 'Human', unitClass: 'Lawman', power: 'wip' },
  'gurei_oni': { id: 'gurei_oni', name: 'Gurei-Oni', shortName: 'Gurei-Oni', type: 'hero', figures: 1, life: 4, move: 5, range: 1, attack: 4, defense: 4, height: 7, size: 'large', points: 100, letter: 'G', species: 'Ogre', unitClass: 'Guard', power: 'wip' },
  'hatamoto_taro': { id: 'hatamoto_taro', name: 'Hatamoto Taro', shortName: 'Hatamoto Taro', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 2, defense: 2, height: 5, points: 130, letter: 'H', species: 'Human', unitClass: 'Samurai', power: 'wip' },
  'isamu': { id: 'isamu', name: 'Isamu', shortName: 'Isamu', type: 'hero', figures: 1, life: 1, move: 6, range: 1, attack: 3, defense: 1, height: 4, points: 10, letter: 'I', species: 'Human', unitClass: 'Ninja', power: 'wip' },
  'iskra_esenwein': { id: 'iskra_esenwein', name: 'Iskra Esenwein', shortName: 'Iskra Esenwein', type: 'hero', figures: 1, life: 4, move: 6, range: 1, attack: 3, defense: 3, height: 4, points: 50, letter: 'I', species: 'Undead', unitClass: 'Duchess', power: 'wip' },
  'james_murphy': { id: 'james_murphy', name: 'James Murphy', shortName: 'James Murphy', type: 'hero', figures: 1, life: 5, move: 5, range: 7, attack: 2, defense: 2, height: 4, points: 75, letter: 'J', species: 'Human', unitClass: 'Lawman', power: 'wip' },
  'johnny_shotgun_sullivan': { id: 'johnny_shotgun_sullivan', name: 'Johnny "Shotgun" Sullivan', shortName: 'Johnny "Shotgun" Sullivan', type: 'hero', figures: 1, life: 5, move: 5, range: 5, attack: 2, defense: 2, height: 5, points: 65, letter: 'J', species: 'Human', unitClass: 'Lawman', power: 'wip' },
  'jorhdawn': { id: 'jorhdawn', name: 'Jorhdawn', shortName: 'Jorhdawn', type: 'hero', figures: 1, life: 6, move: 5, range: 1, attack: 3, defense: 2, height: 4, points: 100, letter: 'J', species: 'Elf', unitClass: 'Wizard', power: 'wip' },
  'kaemon_awa': { id: 'kaemon_awa', name: 'Kaemon Awa', shortName: 'Kaemon Awa', type: 'hero', figures: 1, life: 4, move: 5, range: 7, attack: 4, defense: 4, height: 5, points: 120, letter: 'K', species: 'Human', unitClass: 'Samurai', power: 'wip' },
  'kato_katsuro': { id: 'kato_katsuro', name: 'Kato Katsuro', shortName: 'Kato Katsuro', type: 'hero', figures: 1, life: 5, move: 6, range: 1, attack: 4, defense: 4, height: 5, points: 200, letter: 'K', species: 'Human', unitClass: '', power: 'wip' },
  'kee_mo_shi': { id: 'kee_mo_shi', name: 'Kee-Mo-Shi', shortName: 'Kee-Mo-Shi', type: 'hero', figures: 1, life: 4, move: 6, range: 1, attack: 4, defense: 4, height: 6, points: 130, letter: 'K', species: 'Marro', unitClass: 'Warwitch', power: 'wip' },
  'kelda_the_kyrie_warrior': { id: 'kelda_the_kyrie_warrior', name: 'Kelda the Kyrie Warrior', shortName: 'Kelda', type: 'hero', figures: 1, life: 5, move: 6, range: 1, attack: 2, defense: 3, height: 5, points: 80, letter: 'K', species: 'Kyrie', unitClass: 'Warrior', power: 'wip' },
  'khosumet_the_darklord': { id: 'khosumet_the_darklord', name: 'Khosumet the Darklord', shortName: 'Khosumet', type: 'hero', figures: 1, life: 3, move: 6, range: 1, attack: 3, defense: 3, height: 5, points: 75, letter: 'K', species: '', unitClass: 'Darklord', power: 'wip' },
  'knights_of_weston': { id: 'knights_of_weston', name: 'Knights of Weston', shortName: 'Knights of Weston', type: 'squad', figures: 4, life: 1, move: 4, range: 1, attack: 3, defense: 4, height: 5, points: 70, letter: 'K', species: 'Human', unitClass: 'Knights', common: true, power: 'wip' },
  'kozuke_samurai': { id: 'kozuke_samurai', name: 'Kozuke Samurai', shortName: 'Kozuke Samurai', type: 'squad', figures: 3, life: 1, move: 5, range: 1, attack: 5, defense: 3, height: 4, points: 100, letter: 'K', species: 'Human', unitClass: 'Samurai', power: 'wip' },
  'krug': { id: 'krug', name: 'Krug', shortName: 'Krug', type: 'hero', figures: 1, life: 8, move: 5, range: 1, attack: 2, defense: 3, height: 8, size: 'huge', points: 120, letter: 'K', species: 'Beast', unitClass: 'Troll', power: 'wip' },
  'kumiko': { id: 'kumiko', name: 'Kumiko', shortName: 'Kumiko', type: 'hero', figures: 1, life: 3, move: 6, range: 1, attack: 3, defense: 5, height: 4, points: 80, letter: 'K', species: 'Human', unitClass: 'Ninja', power: 'wip' },
  'kyntela_gwyn': { id: 'kyntela_gwyn', name: 'Kyntela Gwyn', shortName: 'Kyntela Gwyn', type: 'hero', figures: 1, life: 2, move: 5, range: 1, attack: 2, defense: 2, height: 4, points: 20, letter: 'K', species: 'Elf', unitClass: 'Wizard', power: 'wip' },
  'laglor': { id: 'laglor', name: 'Laglor', shortName: 'Laglor', type: 'hero', figures: 1, life: 6, move: 5, range: 7, attack: 3, defense: 3, height: 5, points: 110, letter: 'L', species: 'Primadon', unitClass: 'Primadon', power: 'wip' },
  'macdirk_warriors': { id: 'macdirk_warriors', name: 'MacDirk Warriors', shortName: 'MacDirk Warriors', type: 'squad', figures: 4, life: 1, move: 5, range: 1, attack: 2, defense: 2, height: 5, points: 80, letter: 'M', species: 'Human', unitClass: 'Warriors', common: true, power: 'wip' },
  'major_q10': { id: 'major_q10', name: 'Major Q10', shortName: 'Major Q10', type: 'hero', figures: 1, life: 4, move: 5, range: 8, attack: 4, defense: 5, height: 6, size: 'large', points: 150, letter: 'M', species: 'Soulborg', unitClass: 'Major', power: 'wip' },
  'major_x17': { id: 'major_x17', name: 'Major X17', shortName: 'Major X17', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 4, defense: 3, height: 5, points: 100, letter: 'M', species: 'Soulborg', unitClass: 'Major', power: 'wip' },
  'marcu_esenwein': { id: 'marcu_esenwein', name: 'Marcu Esenwein', shortName: 'Marcu Esenwein', type: 'hero', figures: 1, life: 6, move: 7, range: 1, attack: 4, defense: 1, height: 4, points: 20, letter: 'M', species: 'Undead', unitClass: 'Devourer', power: 'wip' },
  'marcus_decimus_gallus': { id: 'marcus_decimus_gallus', name: 'Marcus Decimus Gallus', shortName: 'Marcus Decimus Gallus', type: 'hero', figures: 1, life: 6, move: 5, range: 1, attack: 3, defense: 3, height: 5, points: 100, letter: 'M', species: 'Human', unitClass: 'Warlord', power: 'wip' },
  'marrden_hounds': { id: 'marrden_hounds', name: 'Marrden Hounds', shortName: 'Marrden Hounds', type: 'squad', figures: 3, life: 1, move: 1, range: 1, attack: 3, defense: 5, height: 4, size: 'large', points: 90, letter: 'M', species: 'Wild', unitClass: 'Hunters', common: true, power: 'wip' },
  'marrden_nagrubs': { id: 'marrden_nagrubs', name: 'Marrden Nagrubs', shortName: 'Marrden Nagrubs', type: 'squad', figures: 3, life: 1, move: 6, range: 1, attack: 2, defense: 2, height: 3, size: 'small', points: 30, letter: 'M', species: '', unitClass: 'Nagrubs', common: true, power: 'wip' },
  'marro_dividers': { id: 'marro_dividers', name: 'Marro Dividers', shortName: 'Marro Dividers', type: 'squad', figures: 3, life: 1, move: 5, range: 1, attack: 3, defense: 3, height: 4, points: 50, letter: 'M', species: 'Marro', unitClass: 'Dividers', common: true, power: 'wip' },
  'marro_drones': { id: 'marro_drones', name: 'Marro Drones', shortName: 'Marro Drones', type: 'squad', figures: 3, life: 1, move: 6, range: 1, attack: 3, defense: 3, height: 5, points: 50, letter: 'M', species: 'Marro', unitClass: 'Drone', common: true, power: 'wip' },
  'marro_drudge': { id: 'marro_drudge', name: 'Marro Drudge', shortName: 'Marro Drudge', type: 'squad', figures: 3, life: 1, move: 5, range: 5, attack: 2, defense: 2, height: 4, points: 50, letter: 'M', species: 'Marro', unitClass: 'Hunters', common: true, power: 'wip' },
  'marro_hive': { id: 'marro_hive', name: 'Marro Hive', shortName: 'Marro Hive', type: 'hero', figures: 1, life: 6, move: 0, range: 1, attack: 1, defense: 2, height: 17, size: 'huge', points: 160, letter: 'M', species: 'Marro', unitClass: 'Hive', power: 'wip' },
  'marro_stingers': { id: 'marro_stingers', name: 'Marro Stingers', shortName: 'Marro Stingers', type: 'squad', figures: 3, life: 1, move: 5, range: 5, attack: 3, defense: 3, height: 4, points: 60, letter: 'M', species: 'Marro', unitClass: 'Stingers', common: true, power: 'wip' },
  'master_win_chiu_woo': { id: 'master_win_chiu_woo', name: 'Master Win Chiu Woo', shortName: 'Master Win Chiu Woo', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 4, defense: 4, height: 5, points: 140, letter: 'M', species: 'Human', unitClass: 'Monk', power: 'wip' },
  'me_burq_sa': { id: 'me_burq_sa', name: 'Me-Burq-Sa', shortName: 'Me-Burq-Sa', type: 'hero', figures: 1, life: 3, move: 8, range: 6, attack: 3, defense: 3, height: 7, size: 'large', points: 50, letter: 'M', species: 'Marro', unitClass: 'Warlord', power: 'wip' },
  'microcorp_agents': { id: 'microcorp_agents', name: 'Microcorp Agents', shortName: 'Microcorp Agents', type: 'squad', figures: 3, life: 1, move: 5, range: 7, attack: 2, defense: 3, height: 5, points: 100, letter: 'M', species: 'Human', unitClass: 'Agents', common: true, power: 'wip' },
  'migol_ironwill': { id: 'migol_ironwill', name: 'Migol Ironwill', shortName: 'Migol Ironwill', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 2, defense: 4, height: 3, size: 'small', points: 110, letter: 'M', species: 'Dwarf', unitClass: 'Leader', power: 'wip' },
  'minions_of_utgar': { id: 'minions_of_utgar', name: 'Minions of Utgar', shortName: 'Minions of Utgar', type: 'squad', figures: 3, life: 1, move: 4, range: 1, attack: 2, defense: 6, height: 6, points: 110, letter: 'M', species: 'Kyrie', unitClass: 'Minions', common: true, power: 'wip' },
  'mohican_river_tribe': { id: 'mohican_river_tribe', name: 'Mohican River Tribe', shortName: 'Mohican River Tribe', type: 'squad', figures: 3, life: 1, move: 5, range: 6, attack: 2, defense: 1, height: 5, points: 70, letter: 'M', species: 'Human', unitClass: 'Scouts', common: true, power: 'wip' },
  'moriko': { id: 'moriko', name: 'Moriko', shortName: 'Moriko', type: 'hero', figures: 1, life: 4, move: 6, range: 1, attack: 4, defense: 4, height: 4, points: 110, letter: 'M', species: 'Human', unitClass: 'Ninja', power: 'wip' },
  'morsbane': { id: 'morsbane', name: 'Morsbane', shortName: 'Morsbane', type: 'hero', figures: 1, life: 6, move: 5, range: 1, attack: 3, defense: 2, height: 5, points: 100, letter: 'M', species: 'Elf', unitClass: 'Wizard', power: 'wip' },
  'nakita_agents': { id: 'nakita_agents', name: 'NAKITA AGENTS', shortName: 'NAKITA AGENTS', type: 'squad', figures: 3, life: 1, move: 5, range: 6, attack: 3, defense: 3, height: 4, points: 120, letter: 'N', species: 'Human', unitClass: 'Agents', power: 'wip' },
  'nerak_the_glacian_swog_rider': { id: 'nerak_the_glacian_swog_rider', name: 'Nerak the Glacian Swog Rider', shortName: 'Nerak', type: 'hero', figures: 1, life: 3, move: 8, range: 1, attack: 3, defense: 3, height: 6, size: 'large', points: 50, letter: 'N', species: 'Orc', unitClass: 'Champion', power: 'wip' },
  'ninjas_of_the_northern_wind': { id: 'ninjas_of_the_northern_wind', name: 'Ninjas of the Northern Wind', shortName: 'Ninjas of', type: 'squad', figures: 3, life: 1, move: 6, range: 1, attack: 4, defense: 3, height: 4, points: 110, letter: 'N', species: 'Human', unitClass: 'Ninja', power: 'wip' },
  'obsidian_guards': { id: 'obsidian_guards', name: 'Obsidian Guards', shortName: 'Obsidian Guards', type: 'squad', figures: 3, life: 1, move: 4, range: 1, attack: 4, defense: 4, height: 5, points: 100, letter: 'O', species: 'Moltarn', unitClass: 'Guards', common: true, power: 'wip' },
  'omnicron_repulsors': { id: 'omnicron_repulsors', name: 'Omnicron Repulsors', shortName: 'Omnicron Repulsors', type: 'squad', figures: 3, life: 1, move: 5, range: 7, attack: 1, defense: 3, height: 3, size: 'small', points: 40, letter: 'O', species: 'Soulborg', unitClass: 'Repulsors', common: true, power: 'wip' },
  'omnicron_snipers': { id: 'omnicron_snipers', name: 'Omnicron Snipers', shortName: 'Omnicron Snipers', type: 'squad', figures: 3, life: 1, move: 5, range: 7, attack: 1, defense: 3, height: 5, points: 100, letter: 'O', species: 'Soulborg', unitClass: 'Snipers', common: true, power: 'wip' },
  'ornak': { id: 'ornak', name: 'Ornak', shortName: 'Ornak', type: 'hero', figures: 1, life: 4, move: 6, range: 1, attack: 3, defense: 3, height: 5, points: 100, letter: 'O', species: 'Orc', unitClass: 'Champion', power: 'wip' },
  'parmenio': { id: 'parmenio', name: 'Parmenio', shortName: 'Parmenio', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 3, defense: 3, height: 5, points: 90, letter: 'P', species: 'Human', unitClass: 'Warlord', power: 'wip' },
  'protectors_of_ullar': { id: 'protectors_of_ullar', name: 'Protectors of Ullar', shortName: 'Protectors of Ullar', type: 'squad', figures: 3, life: 1, move: 4, range: 5, attack: 3, defense: 3, height: 6, points: 110, letter: 'P', species: 'Kyrie', unitClass: 'Protectors', common: true, power: 'wip' },
  'quasatch_hunters': { id: 'quasatch_hunters', name: 'Quasatch Hunters', shortName: 'Quasatch Hunters', type: 'squad', figures: 3, life: 1, move: 5, range: 1, attack: 3, defense: 4, height: 5, points: 100, letter: 'Q', species: 'Quasatch', unitClass: 'Hunters', common: true, power: 'wip' },
  'rechets_of_bogdan': { id: 'rechets_of_bogdan', name: 'Rechets of Bogdan', shortName: 'Rechets of Bogdan', type: 'squad', figures: 3, life: 1, move: 6, range: 1, attack: 3, defense: 3, height: 4, points: 50, letter: 'R', species: 'Undead', unitClass: 'Devourer', power: 'wip' },
  'retiarius': { id: 'retiarius', name: 'Retiarius', shortName: 'Retiarius', type: 'hero', figures: 1, life: 4, move: 5, range: 1, attack: 5, defense: 3, height: 5, points: 90, letter: 'R', species: 'Human', unitClass: 'Gladiator', power: 'wip' },
  'roman_archers': { id: 'roman_archers', name: 'Roman Archers', shortName: 'Roman Archers', type: 'squad', figures: 3, life: 1, move: 4, range: 6, attack: 2, defense: 1, height: 5, points: 55, letter: 'R', species: 'Human', unitClass: 'Archers', common: true, power: 'wip' },
  'roman_legionnaires': { id: 'roman_legionnaires', name: 'Roman Legionnaires', shortName: 'Roman Legionnaires', type: 'squad', figures: 4, life: 1, move: 4, range: 1, attack: 3, defense: 2, height: 5, points: 50, letter: 'R', species: 'Human', unitClass: 'Soldier', common: true, power: 'wip' },
  'runa': { id: 'runa', name: 'Runa', shortName: 'Runa', type: 'hero', figures: 1, life: 5, move: 6, range: 1, attack: 3, defense: 3, height: 5, points: 120, letter: 'R', species: 'Kyrie', unitClass: 'Warrior', power: 'wip' },
  'sacred_band': { id: 'sacred_band', name: 'Sacred Band', shortName: 'Sacred Band', type: 'squad', figures: 4, life: 1, move: 4, range: 1, attack: 3, defense: 2, height: 5, points: 50, letter: 'S', species: 'Human', unitClass: 'Soldiers', common: true, power: 'wip' },
  'saylind_the_kyrie_warrior': { id: 'saylind_the_kyrie_warrior', name: 'Saylind the Kyrie Warrior', shortName: 'Saylind', type: 'hero', figures: 1, life: 5, move: 6, range: 1, attack: 3, defense: 3, height: 5, points: 80, letter: 'S', species: 'Kyrie', unitClass: 'Warrior', power: 'wip' },
  'sentinels_of_jandar': { id: 'sentinels_of_jandar', name: 'Sentinels of Jandar', shortName: 'Sentinels of Jandar', type: 'squad', figures: 3, life: 1, move: 4, range: 1, attack: 3, defense: 4, height: 6, points: 110, letter: 'S', species: 'Kyrie', unitClass: 'Sentinels', common: true, power: 'wip' },
  'shades_of_bleakwoode': { id: 'shades_of_bleakwoode', name: 'Shades of Bleakwoode', shortName: 'Shades of Bleakwoode', type: 'squad', figures: 3, life: 1, move: 7, range: 1, attack: 2, defense: 4, height: 5, points: 100, letter: 'S', species: 'Undead', unitClass: 'Devourers', common: true, power: 'wip' },
  'shaolin_monks': { id: 'shaolin_monks', name: 'Shaolin Monks', shortName: 'Shaolin Monks', type: 'squad', figures: 3, life: 1, move: 6, range: 1, attack: 3, defense: 3, height: 5, points: 80, letter: 'S', species: 'Human', unitClass: 'Monks', common: true, power: 'wip' },
  'shiori_swarm_of_the_marro': { id: 'shiori_swarm_of_the_marro', name: 'Shiori (Swarm of the Marro)', shortName: 'Shiori (Swarm of', type: 'hero', figures: 1, life: 3, move: 6, range: 1, attack: 3, defense: 3, height: 4, points: 60, letter: 'S', species: 'Human', unitClass: 'Ninja', power: 'wip' },
  'sir_denrick': { id: 'sir_denrick', name: 'Sir Denrick', shortName: 'Sir Denrick', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 4, defense: 4, height: 5, points: 100, letter: 'S', species: 'Human', unitClass: 'Champion', power: 'wip' },
  'sir_dupuis': { id: 'sir_dupuis', name: 'Sir Dupuis', shortName: 'Sir Dupuis', type: 'hero', figures: 1, life: 6, move: 8, range: 1, attack: 4, defense: 3, height: 6, size: 'large', points: 150, letter: 'S', species: 'Human', unitClass: 'Knight', power: 'wip' },
  'sir_gilbert': { id: 'sir_gilbert', name: 'Sir Gilbert', shortName: 'Sir Gilbert', type: 'hero', figures: 1, life: 6, move: 5, range: 1, attack: 3, defense: 4, height: 5, points: 105, letter: 'S', species: 'Human', unitClass: 'Champion', power: 'wip' },
  'sir_hawthorne': { id: 'sir_hawthorne', name: 'Sir Hawthorne', shortName: 'Sir Hawthorne', type: 'hero', figures: 1, life: 6, move: 5, range: 1, attack: 4, defense: 4, height: 5, points: 90, letter: 'S', species: 'Human', unitClass: 'Champion', power: 'wip' },
  'sonlen': { id: 'sonlen', name: 'Sonlen', shortName: 'Sonlen', type: 'hero', figures: 1, life: 6, move: 5, range: 6, attack: 4, defense: 3, height: 5, points: 160, letter: 'S', species: 'Elf', unitClass: 'Archmage', power: 'wip' },
  'sonya_esenwein': { id: 'sonya_esenwein', name: 'Sonya Esenwein', shortName: 'Sonya Esenwein', type: 'hero', figures: 1, life: 3, move: 6, range: 1, attack: 3, defense: 3, height: 4, points: 45, letter: 'S', species: 'Undead', unitClass: 'Lady', power: 'wip' },
  'spartacus': { id: 'spartacus', name: 'Spartacus', shortName: 'Spartacus', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 6, defense: 4, height: 5, points: 200, letter: 'S', species: 'Human', unitClass: 'Gladiator', power: 'wip' },
  'sudema': { id: 'sudema', name: 'Sudema', shortName: 'Sudema', type: 'hero', figures: 1, life: 4, move: 5, range: 1, attack: 2, defense: 3, height: 5, points: 140, letter: 'S', species: 'Wild', unitClass: 'Queen', power: 'wip' },
  'sujoah': { id: 'sujoah', name: 'Sujoah', shortName: 'Sujoah', type: 'hero', figures: 1, life: 6, move: 8, range: 1, attack: 4, defense: 4, height: 6, size: 'huge', points: 185, letter: 'S', species: 'Insect', unitClass: 'Predator', power: 'wip' },
  'taelord_the_kyrie_warrior': { id: 'taelord_the_kyrie_warrior', name: 'Taelord the Kyrie Warrior', shortName: 'Taelord', type: 'hero', figures: 1, life: 5, move: 5, range: 1, attack: 3, defense: 3, height: 5, points: 180, letter: 'T', species: 'Kyrie', unitClass: 'Warrior', power: 'wip' },
  'tagawa_samurai': { id: 'tagawa_samurai', name: 'Tagawa Samurai', shortName: 'Tagawa Samurai', type: 'squad', figures: 3, life: 1, move: 6, range: 1, attack: 3, defense: 5, height: 5, points: 120, letter: 'T', species: 'Human', unitClass: 'Samurai', power: 'wip' },
  'tagawa_samurai_archers': { id: 'tagawa_samurai_archers', name: 'Tagawa Samurai Archers', shortName: 'Tagawa Samurai Archers', type: 'squad', figures: 3, life: 1, move: 5, range: 6, attack: 2, defense: 3, height: 5, points: 65, letter: 'T', species: 'Human', unitClass: 'Samurai', common: true, power: 'wip' },
  'templar_cavalry': { id: 'templar_cavalry', name: 'Templar Cavalry', shortName: 'Templar Cavalry', type: 'squad', figures: 3, life: 1, move: 8, range: 1, attack: 3, defense: 3, height: 6, size: 'large', points: 120, letter: 'T', species: 'Human', unitClass: 'Knights', common: true, power: 'wip' },
  'the_axegrinders_of_burning_forge': { id: 'the_axegrinders_of_burning_forge', name: 'The Axegrinders of Burning Forge', shortName: 'The Axegrinders of Burning Forge', type: 'squad', figures: 4, life: 1, move: 4, range: 1, attack: 3, defense: 3, height: 3, size: 'small', points: 70, letter: 'T', species: 'Dwarves', unitClass: 'Fighters', common: true, power: 'wip' },
  'the_einar_imperium': { id: 'the_einar_imperium', name: 'The Einar Imperium', shortName: 'The Einar Imperium', type: 'squad', figures: 3, life: 1, move: 5, range: 1, attack: 3, defense: 3, height: 5, points: 140, letter: 'T', species: 'Kyrie', unitClass: 'Soldiers', common: true, power: 'wip' },
  'tor_kul_na': { id: 'tor_kul_na', name: 'Tor-Kul-Na', shortName: 'Tor-Kul-Na', type: 'hero', figures: 1, life: 6, move: 6, range: 1, attack: 6, defense: 5, height: 11, size: 'huge', points: 220, letter: 'T', species: 'Marro', unitClass: '', power: 'wip' },
  'tornak': { id: 'tornak', name: 'Tornak', shortName: 'Tornak', type: 'hero', figures: 1, life: 3, move: 7, range: 1, attack: 4, defense: 5, height: 6, size: 'large', points: 100, letter: 'T', species: 'Orc', unitClass: 'Champion', power: 'wip' },
  'tul_bak_ra': { id: 'tul_bak_ra', name: 'Tul-Bak-Ra', shortName: 'Tul-Bak-Ra', type: 'hero', figures: 1, life: 6, move: 5, range: 1, attack: 4, defense: 4, height: 5, points: 130, letter: 'T', species: 'Marro', unitClass: 'Overlord', power: 'wip' },
  'ulginesh': { id: 'ulginesh', name: 'Ulginesh', shortName: 'Ulginesh', type: 'hero', figures: 1, life: 5, move: 7, range: 6, attack: 3, defense: 3, height: 6, size: 'large', points: 150, letter: 'U', species: 'Elf', unitClass: 'Wizard', power: 'wip' },
  'valguard': { id: 'valguard', name: 'Valguard', shortName: 'Valguard', type: 'hero', figures: 1, life: 7, move: 5, range: 1, attack: 2, defense: 4, height: 5, points: 110, letter: 'V', species: 'Human', unitClass: 'Warlord', power: 'wip' },
  'venoc_vipers': { id: 'venoc_vipers', name: 'Venoc Vipers', shortName: 'Venoc Vipers', type: 'squad', figures: 3, life: 1, move: 7, range: 1, attack: 3, defense: 0, height: 5, points: 40, letter: 'V', species: '', unitClass: 'Vipers', common: true, power: 'wip' },
  'venoc_warlord': { id: 'venoc_warlord', name: 'Venoc Warlord', shortName: 'Venoc Warlord', type: 'hero', figures: 1, life: 6, move: 7, range: 1, attack: 4, defense: 3, height: 6, points: 120, letter: 'V', species: 'Viper', unitClass: 'Warlord', power: 'wip' },
  'warden_816': { id: 'warden_816', name: 'Warden 816', shortName: 'Warden 816', type: 'hero', figures: 1, life: 2, move: 5, range: 7, attack: 3, defense: 6, height: 4, points: 90, letter: 'W', species: 'Soulborg', unitClass: 'Warden', power: 'wip' },
  'warriors_of_ashra': { id: 'warriors_of_ashra', name: 'Warriors of Ashra', shortName: 'Warriors of Ashra', type: 'squad', figures: 3, life: 1, move: 5, range: 1, attack: 3, defense: 3, height: 4, points: 50, letter: 'W', species: 'Elves', unitClass: 'Warriors', common: true, power: 'wip' },
  'wo_sa_ga': { id: 'wo_sa_ga', name: 'Wo-Sa-Ga', shortName: 'Wo-Sa-Ga', type: 'hero', figures: 1, life: 4, move: 6, range: 1, attack: 6, defense: 4, height: 10, size: 'huge', points: 135, letter: 'W', species: 'Marro', unitClass: 'Marro', power: 'wip' },
  'wolves_of_badru': { id: 'wolves_of_badru', name: 'Wolves of Badru', shortName: 'Wolves of Badru', type: 'squad', figures: 3, life: 1, move: 6, range: 1, attack: 3, defense: 3, height: 3, size: 'small', points: 80, letter: 'W', species: 'Wolves', unitClass: 'Hunters', common: true, power: 'wip' },
  'zelrig': { id: 'zelrig', name: 'Zelrig', shortName: 'Zelrig', type: 'hero', figures: 1, life: 6, move: 6, range: 1, attack: 4, defense: 4, height: 11, size: 'huge', points: 185, letter: 'Z', species: 'Dragon', unitClass: 'Dragon', power: 'wip' },
  'zetacron': { id: 'zetacron', name: 'Zetacron', shortName: 'Zetacron', type: 'hero', figures: 1, life: 2, move: 5, range: 8, attack: 2, defense: 4, height: 7, size: 'large', points: 60, letter: 'Z', species: 'Soulborg', unitClass: 'Scout', power: 'wip' },
  'zombies_of_morindan': { id: 'zombies_of_morindan', name: 'Zombies of Morindan', shortName: 'Zombies of Morindan', type: 'squad', figures: 3, life: 1, move: 4, range: 1, attack: 2, defense: 3, height: 5, points: 60, letter: 'Z', species: 'Undead', unitClass: 'Savages', common: true, power: 'wip' },
};

export const GENERATED_CLASSIC_IDENTITY: Record<string, { general: string; personality: string; world: string }> = {
  '10th_regiment_of_foot': { general: 'Einar', personality: 'Disciplined', world: '' },
  '4th_massachusetts_line': { general: 'Jandar', personality: 'Valiant', world: '' },
  'acolarh': { general: 'Ullar', personality: 'Valiant', world: '' },
  'agent_skahen': { general: 'Vydar', personality: 'Tricky', world: '' },
  'alastair_macdirk': { general: 'Jandar', personality: 'Valiant', world: '' },
  'anubian_wolves': { general: 'Utgar', personality: 'Devourers Relentless', world: '' },
  'arkmer': { general: 'Ullar', personality: 'Tricky', world: '' },
  'armoc_vipers': { general: 'Ullar', personality: 'Protectors Relentless', world: '' },
  'ashigaru_harquebus': { general: 'Einar', personality: 'Disciplined', world: '' },
  'ashigaru_yari': { general: 'Einar', personality: 'Disciplined', world: '' },
  'atlaga_the_kyrie_warrior': { general: 'Ullar', personality: 'Confident', world: '' },
  'aubrien_archers': { general: 'Ullar', personality: 'Precise', world: '' },
  'blastatrons': { general: 'Vydar', personality: 'Disciplined', world: '' },
  'brave_arrow': { general: 'Aquilla', personality: 'Fearsome', world: '' },
  'brunak': { general: 'Utgar', personality: 'Ferocious', world: '' },
  'capuan_gladiators': { general: 'Einar', personality: 'Rebellious', world: '' },
  'chardris': { general: 'Ullar', personality: 'Valiant', world: '' },
  'charos': { general: 'Ullar', personality: 'Valiant', world: '' },
  'concan_the_kyrie_warrior': { general: 'Jandar', personality: 'Valiant', world: '' },
  'crixus': { general: 'Einar', personality: 'Rebellious', world: '' },
  'cyprien_esenwein': { general: 'Utgar', personality: 'Terrifying', world: '' },
  'deadeye_dan': { general: 'Ullar', personality: 'Precise', world: '' },
  'deathstalkers': { general: 'Utgar', personality: 'Wild', world: '' },
  'deathwalker_7000': { general: 'Utgar', personality: 'Tricky', world: '' },
  'deathwalker_8000': { general: 'Utgar', personality: 'Precise', world: '' },
  'dumutef_guard': { general: 'Utgar', personality: 'Relentless', world: '' },
  'dund': { general: 'Vydar', personality: 'Tricky', world: '' },
  'dzu_teh': { general: 'Jandar', personality: '', world: '' },
  'elite_onyx_vipers': { general: 'Ullar', personality: 'Scouts', world: '' },
  'emirroon': { general: 'Ullar', personality: 'Tricky', world: '' },
  'empress_kiova': { general: 'Einar', personality: 'Disciplined', world: '' },
  'fyorlag_spiders': { general: 'Aquilla', personality: 'Scouts', world: '' },
  'gladiatrons': { general: 'Vydar', personality: 'Disciplined', world: '' },
  'gorillinators': { general: 'Vydar', personality: 'Tricky', world: '' },
  'granite_guardians': { general: 'Aquilla', personality: 'Dauntless', world: '' },
  'grok_riders': { general: 'Utgar', personality: 'Hunters', world: '' },
  'guilty_mccreech': { general: 'Einar', personality: 'Wild', world: '' },
  'gurei_oni': { general: 'Einar', personality: 'Tormenting', world: '' },
  'hatamoto_taro': { general: 'Einar', personality: 'Disciplined', world: '' },
  'isamu': { general: 'Utgar', personality: 'Disciplined', world: '' },
  'iskra_esenwein': { general: 'Utgar', personality: 'Terrifying', world: '' },
  'james_murphy': { general: 'Vydar', personality: 'Disciplined', world: '' },
  'johnny_shotgun_sullivan': { general: 'Jandar', personality: 'Tricky', world: '' },
  'jorhdawn': { general: 'Ullar', personality: 'Valiant', world: '' },
  'kaemon_awa': { general: 'Einar', personality: 'Disciplined', world: '' },
  'kato_katsuro': { general: 'Einar', personality: 'Disciplined', world: '' },
  'kee_mo_shi': { general: 'Utgar', personality: 'Tricky', world: '' },
  'kelda_the_kyrie_warrior': { general: 'Jandar', personality: 'Merciful', world: '' },
  'khosumet_the_darklord': { general: 'Utgar', personality: 'Relentless', world: '' },
  'knights_of_weston': { general: 'Jandar', personality: 'Valiant', world: '' },
  'kozuke_samurai': { general: 'Einar', personality: 'Disciplined', world: '' },
  'krug': { general: 'Utgar', personality: 'Relentless', world: '' },
  'kumiko': { general: 'Jandar', personality: 'Tricky', world: '' },
  'kyntela_gwyn': { general: 'Ullar', personality: 'Valiant', world: '' },
  'laglor': { general: 'Vydar', personality: 'Precise', world: '' },
  'macdirk_warriors': { general: 'Jandar', personality: 'Wild', world: '' },
  'major_q10': { general: 'Vydar', personality: 'Merciful', world: '' },
  'major_x17': { general: 'Vydar', personality: 'Disciplined', world: '' },
  'marcu_esenwein': { general: 'Utgar', personality: 'Terrifying', world: '' },
  'marcus_decimus_gallus': { general: 'Einar', personality: 'Disciplined', world: '' },
  'marrden_hounds': { general: 'Utgar', personality: '', world: '' },
  'marrden_nagrubs': { general: 'Utgar', personality: '', world: '' },
  'marro_dividers': { general: 'Utgar', personality: 'Wild', world: '' },
  'marro_drones': { general: 'Utgar', personality: 'Wild', world: '' },
  'marro_drudge': { general: 'Utgar', personality: 'Wild', world: '' },
  'marro_hive': { general: 'Utgar', personality: 'Terrifying', world: '' },
  'marro_stingers': { general: 'Utgar', personality: 'Wild', world: '' },
  'master_win_chiu_woo': { general: 'Aquilla', personality: 'Disciplined', world: '' },
  'me_burq_sa': { general: 'Utgar', personality: 'Wild', world: '' },
  'microcorp_agents': { general: 'Vydar', personality: 'Tricky', world: '' },
  'migol_ironwill': { general: 'Aquilla', personality: 'Resolute', world: '' },
  'minions_of_utgar': { general: 'Utgar', personality: 'Relentless', world: '' },
  'mohican_river_tribe': { general: 'Aquilla', personality: 'Fearsome', world: '' },
  'moriko': { general: 'Ullar', personality: 'Disciplined', world: '' },
  'morsbane': { general: 'Ullar', personality: 'Tricky', world: '' },
  'nakita_agents': { general: 'Vydar', personality: 'Tricky', world: '' },
  'nerak_the_glacian_swog_rider': { general: 'Utgar', personality: 'Wild', world: '' },
  'ninjas_of_the_northern_wind': { general: 'Einar', personality: 'Disciplined', world: '' },
  'obsidian_guards': { general: 'Utgar', personality: 'Ferocious', world: '' },
  'omnicron_repulsors': { general: 'Jandar', personality: 'Precise', world: '' },
  'omnicron_snipers': { general: 'Jandar', personality: 'Precise', world: '' },
  'ornak': { general: 'Utgar', personality: 'Wild', world: '' },
  'parmenio': { general: 'Einar', personality: 'Disciplined', world: '' },
  'protectors_of_ullar': { general: 'Ullar', personality: 'Confident', world: '' },
  'quasatch_hunters': { general: 'Aquilla', personality: 'Ferocious', world: '' },
  'rechets_of_bogdan': { general: 'Utgar', personality: 'Terrifying', world: '' },
  'retiarius': { general: 'Einar', personality: 'Rebellious', world: '' },
  'roman_archers': { general: 'Einar', personality: 'Disciplined', world: '' },
  'roman_legionnaires': { general: 'Einar', personality: 'Disciplined', world: '' },
  'runa': { general: 'Utgar', personality: 'Tricky', world: '' },
  'sacred_band': { general: 'Einar', personality: 'Disciplined', world: '' },
  'saylind_the_kyrie_warrior': { general: 'Ullar', personality: 'Valiant', world: '' },
  'sentinels_of_jandar': { general: 'Jandar', personality: 'Valiant', world: '' },
  'shades_of_bleakwoode': { general: 'Utgar', personality: 'Terrifying', world: '' },
  'shaolin_monks': { general: 'Ullar', personality: 'Disciplined', world: '' },
  'shiori_swarm_of_the_marro': { general: 'Einar', personality: 'Tricky', world: '' },
  'sir_denrick': { general: 'Jandar', personality: 'Valiant', world: '' },
  'sir_dupuis': { general: 'Jandar', personality: 'Valiant', world: '' },
  'sir_gilbert': { general: 'Jandar', personality: 'Valiant', world: '' },
  'sir_hawthorne': { general: 'Utgar', personality: 'Relentless', world: '' },
  'sonlen': { general: 'Ullar', personality: 'Tricky', world: '' },
  'sonya_esenwein': { general: 'Utgar', personality: 'Terrifying', world: '' },
  'spartacus': { general: 'Einar', personality: 'Rebellious', world: '' },
  'sudema': { general: 'Vydar', personality: 'Undead', world: '' },
  'sujoah': { general: 'Aquilla', personality: 'Relentless', world: '' },
  'taelord_the_kyrie_warrior': { general: 'Utgar', personality: 'Relentless', world: '' },
  'tagawa_samurai': { general: 'Einar', personality: 'Disciplined', world: '' },
  'tagawa_samurai_archers': { general: 'Einar', personality: 'Disciplined', world: '' },
  'templar_cavalry': { general: 'Jandar', personality: 'Valiant', world: '' },
  'the_axegrinders_of_burning_forge': { general: 'Aquilla', personality: 'Fearless', world: '' },
  'the_einar_imperium': { general: 'Einar', personality: 'Disciplined', world: '' },
  'tor_kul_na': { general: 'Utgar', personality: 'Terrifying', world: '' },
  'tornak': { general: 'Utgar', personality: 'Tricky', world: '' },
  'tul_bak_ra': { general: 'Utgar', personality: 'Terrifying', world: '' },
  'ulginesh': { general: 'Ullar', personality: 'Tricky', world: '' },
  'valguard': { general: 'Einar', personality: 'Wild', world: '' },
  'venoc_vipers': { general: 'Ullar', personality: 'Relentless', world: '' },
  'venoc_warlord': { general: 'Ullar', personality: 'Relentless', world: '' },
  'warden_816': { general: 'Utgar', personality: 'Tricky', world: '' },
  'warriors_of_ashra': { general: 'Ullar', personality: 'Tricky', world: '' },
  'wo_sa_ga': { general: 'Utgar', personality: 'Terrifying', world: '' },
  'wolves_of_badru': { general: 'Utgar', personality: 'Relentless', world: '' },
  'zelrig': { general: 'Einar', personality: 'Disciplined', world: '' },
  'zetacron': { general: 'Jandar', personality: 'Precise', world: '' },
  'zombies_of_morindan': { general: 'Utgar', personality: 'Terrifying', world: '' },
};
