// HeroScape — public barrel for the engine (slice 2: Master Game rounds).

export {
  initialState,
  createInitialStateForHost,
  addPlayer,
  removePlayer,
  applyAction,
  aiNextAction,
  aiPendingSeat,
  aiEngineAction,
  livingSeats,
  initiativeReadySeats,
  getActivePlayerId,
  getOrderedPlayerIds,
  computeHistory,
  projectStateForViewer,
  getActiveCardUid,
  legalDestinations,
  legalStepHexes,
  movementRangeHexes,
  grappleDestinations,
  legalTargets,
  canFireLine,
  fireLineSpaces,
  fireLineTargets,
  fireLineDefenders,
  canExplosion,
  explosionTargets,
  explosionDefenders,
  canMindShackle,
  mindShackleTargets,
  canChomp,
  chompTargets,
  canGrenade,
  grenadeTargets,
  grenadeDefenders,
  // Airborne Elite THE DROP (slice 8) — availability + legal-landing helpers.
  canTheDrop,
  theDropHexes,
  // Big Heroes special powers (slice 8b) — target/availability helpers for the board.
  iceShardTargets,
  queglixTargets,
  queglixDiceLeft,
  wildSwingTargets,
  wildSwingDefenders,
  acidBreathTargets,
  canAcidBreath,
  throwTargets,
  canThrow,
  throwLandingHexes,
  carryPassengers,
  placeableHexes,
  placeable2Leads,
  orientationOptions,
  mapSupportsCount,
  teamBudgetForSeat,
  teamSpentInDraft,
  teamRemainingInDraft,
  POINT_BUDGETS,
  DEFAULT_POINT_BUDGET,
  MIN_POINT_BUDGET,
  MAX_POINT_BUDGET,
  attackDiceRequirements,
  heightAdvantage,
  effectiveAttackDice,
  effectiveDefenseDice,
  auraBuffedFigureIds,
  effectiveMove,
  effectiveRange,
  moveConsequences,
  stepConsequences,
  figureLabel,
  cardDef,
  STATE_VERSION,
  LOG_MAX,
} from './engine';
export type { EffectiveStat } from './engine';

export { HS_CARDS, HS_DRAFT_POOL, SLICE1_ARMIES, COMBAT_DIE_FACES, HS_GLYPHS, POWER_DESCRIPTIONS, CARD_IDENTITY, CLASSIC_OVERRIDES, effectiveCardDef } from './content';
export type { HSGlyphDef, HSGlyphKind } from './content';

export { MAPS, TRAINING_FIELD, THE_KNOLL, FORD_CROSSING, parseMap } from './maps';
export type { HSMap, HSGlyphPlacement } from './maps';

export {
  hexKey,
  parseHexKey,
  offsetToAxial,
  axialToOffset,
  neighborKeys,
  hexDistance,
  rangeDistance,
  reachableDestinations,
  stepCost,
  canStepUp,
  areEngaged,
  computeFall,
  hexToPixel,
  hexCorners,
  segmentCrossesHex,
  hasLineOfSight,
  hasLineOfSight3D,
  isoTopCenter,
  isoBaseCenter,
  isoTopHexCorners,
  isoSideFaces,
  isoDrawOrderKey,
  isoSortByDepth,
  isoSceneBounds,
  ISO_ROTATE_DEG,
  ISO_SQUASH,
  ISO_LEVEL_H,
} from './board';
export type { Occupancy, Pixel, FallTier, ReachOptions, IsoSideFace } from './board';

export type {
  Axial,
  HexKey,
  HexCell,
  Terrain,
  CombatFace,
  HSCardType,
  HSCardDef,
  OrderMarkerValue,
  OrderMarker,
  ArmyCardInstance,
  Figure,
  HSPlayer,
  HSLogEntry,
  InitiativeAttempt,
  LastAttack,
  LastRoll,
  HSPhase,
  HSSubPhase,
  HSState,
  HSAction,
  HSResult,
  HSGlyph,
  HSGlyphId,
  HSPendingChoice,
  HSChoiceResolution,
  HSMode,
  HSEdition,
  HSDraftState,
} from './types';
