// Shared glossary for Marvel Legendary card game interactions.
// Referenced by the sandbox Rules tab (and later the in-game modal).

export type KeywordCategory =
  | 'Turn Flow'
  | 'Keywords'
  | 'Card Types'
  | 'Zones'
  | 'Win / Loss';

export type KeywordEntry = {
  term: string;
  category: KeywordCategory;
  definition: string;
};

export const KEYWORDS: KeywordEntry[] = [

  // ── Turn Flow ──────────────────────────────────────────────────────────────
  {
    term: 'Turn order',
    category: 'Turn Flow',
    definition:
      '1. Mastermind draws the top card of the Villain Deck (villain/henchman enters the city; Scheme Twist or Master Strike fires). ' +
      '2. Active player plays hero cards from hand, then buys from HQ and/or fights city/mastermind in any order. ' +
      '3. Click End Turn: unplayed hand and played cards go to discard; draw 6 new cards.',
  },
  {
    term: 'Playing a card',
    category: 'Turn Flow',
    definition:
      'Click a hero card in your hand to play it. Its Strike and Recruit are added to your turn pools. ' +
      'Class and team synergies fire automatically when conditions are met.',
  },
  {
    term: 'Buying a hero',
    category: 'Turn Flow',
    definition:
      'Spend Recruit equal to the card\'s cost to take it from the HQ into your discard pile. ' +
      'The slot immediately refills from the Hero Deck.',
  },
  {
    term: 'Fighting a villain',
    category: 'Turn Flow',
    definition:
      'Spend Strike ≥ the villain\'s Attack value. The villain goes to your discard (scoring its VP). ' +
      'Any bystanders attached to it are also rescued.',
  },
  {
    term: 'Fighting the mastermind',
    category: 'Turn Flow',
    definition:
      'Spend Strike ≥ the mastermind\'s Attack value to score one hit. After four total hits (across any turns / players) the heroes win.',
  },

  // ── Keywords ───────────────────────────────────────────────────────────────
  {
    term: 'Gaining a card',
    category: 'Keywords',
    definition:
      'When a card effect says you "gain" a card, put that card directly into your discard pile — not into your hand. ' +
      'Example: "Gain a Wound" = take the top card of the Wound Deck and place it in your discard pile.',
  },
  {
    term: 'Ambush',
    category: 'Keywords',
    definition:
      'Fires the moment a villain or henchman enters the city, before the active player can act. ' +
      'Example: "Ambush: Each player gains a Wound" — every player immediately puts a Wound in their discard.',
  },
  {
    term: 'Escape',
    category: 'Keywords',
    definition:
      'Fires when a villain is pushed off the Bridge (slot 5) of the city. Three things happen in order: ' +
      '(1) The escaped villain KOs the highest-cost hero (cost 6 or less) from the HQ; that slot refills immediately. ' +
      '(2) If the villain had captured Bystanders, each player must discard one card from their hand — those Bystanders are lost in the Escape Pile. ' +
      '(3) If the villain\'s card has a printed "Escape" effect, it fires now.',
  },
  {
    term: 'Strike (Attack)',
    category: 'Keywords',
    definition:
      'The red claw number on villain, henchman, and mastermind cards. ' +
      'Your total Strike pool for the turn must equal or exceed it to fight.',
  },
  {
    term: 'Recruit',
    category: 'Keywords',
    definition:
      'The gold coin resource generated by playing hero cards. Spend it to buy heroes from the HQ or recruit Sidekicks / Officers.',
  },
  {
    term: 'KO',
    category: 'Keywords',
    definition:
      'Remove a card permanently from the game — it goes to the KO pile and is never shuffled back into any deck. ' +
      'Fired Master Strikes and heroes KO\'d by villain escapes go here.',
  },
  {
    term: 'Rescue a bystander',
    category: 'Keywords',
    definition:
      'Take one or more Bystander cards into your discard. Each is worth 1 VP at end of game. ' +
      'Bystanders are rescued when you defeat a villain that had one attached, or by certain hero abilities.',
  },

  // ── Card Types ─────────────────────────────────────────────────────────────
  {
    term: 'Wound',
    category: 'Card Types',
    definition:
      'A junk card added to your discard when certain Ambush / Master Strike effects fire. ' +
      'Wounds have no ability — they clog your hand and dilute your draws.',
  },
  {
    term: 'Bystander',
    category: 'Card Types',
    definition:
      'Worth 1 VP. Shuffled into the Villain Deck at game start; villains that enter the city may capture one. ' +
      'Rescue them by defeating the villain or via hero abilities.',
  },
  {
    term: 'Scheme Twist',
    category: 'Card Types',
    definition:
      'When drawn from the Villain Deck it advances the Scheme\'s threat meter by one. ' +
      'Filling the meter triggers the scheme\'s loss condition.',
  },
  {
    term: 'Master Strike',
    category: 'Card Types',
    definition:
      'When drawn from the Villain Deck it fires the mastermind\'s special global effect against all players, ' +
      'then the card is KO\'d (removed from game).',
  },
  {
    term: 'Sidekick',
    category: 'Card Types',
    definition:
      'Generic hero (1 Recruit). Available in unlimited supply from the Sidekick pile for 1 Recruit. ' +
      'Good early-game buy when you can\'t afford HQ cards.',
  },
  {
    term: 'S.H.I.E.L.D. Officer',
    category: 'Card Types',
    definition:
      'Generic hero (3 Recruit, 2 Strike, 1 Recruit). Available in unlimited supply for 3 Recruit. ' +
      'Reliable mid-game filler for Strike when hero synergies aren\'t there.',
  },
  {
    term: 'S.H.I.E.L.D. Trooper',
    category: 'Card Types',
    definition:
      'Starter card (1 Strike). Everyone starts with two Troopers in their opening deck. Provides early Strike.',
  },
  {
    term: 'S.H.I.E.L.D. Agent',
    category: 'Card Types',
    definition:
      'Starter card (1 Recruit). Everyone starts with three Agents in their opening deck. Provides early Recruit.',
  },

  // ── Zones ──────────────────────────────────────────────────────────────────
  {
    term: 'City',
    category: 'Zones',
    definition:
      'Five slots on the board. Villains enter at the Sewers (rightmost) and age left toward the Bridge (leftmost / escape edge). ' +
      'When a new villain enters and all five slots are full, the Bridge card escapes.',
  },
  {
    term: 'HQ',
    category: 'Zones',
    definition:
      'Five hero cards available for purchase. Replenishes from the Hero Deck immediately when a card is recruited.',
  },
  {
    term: 'Escaped pile',
    category: 'Zones',
    definition:
      'Face-up pile where villains go after escaping the Bridge. Any Bystanders they carried are lost here (not rescuable). ' +
      'Accumulating too many escapes may trigger a loss condition depending on the active scheme.',
  },
  {
    term: 'KO pile',
    category: 'Zones',
    definition:
      'Cards removed permanently from the game. Visible count shown in the top-left of the board.',
  },
  {
    term: 'Villain Deck',
    category: 'Zones',
    definition:
      'Shuffled stack containing villains, henchmen, bystanders, Scheme Twists, and Master Strikes. ' +
      'The mastermind draws from it at the start of every turn.',
  },

  // ── Win / Loss ─────────────────────────────────────────────────────────────
  {
    term: 'Win — defeat the mastermind',
    category: 'Win / Loss',
    definition:
      'Land four hits on the mastermind (across any turns / any players). Heroes win immediately.',
  },
  {
    term: 'Loss — scheme twists',
    category: 'Win / Loss',
    definition:
      'Each scheme has a twist limit shown on its card. When the threat meter is full the scheme fires its loss condition.',
  },
  {
    term: 'Loss — too many escapes',
    category: 'Win / Loss',
    definition:
      'Some schemes end the game when a certain number of villains escape the city via the Bridge.',
  },
  {
    term: 'VP scoring',
    category: 'Win / Loss',
    definition:
      'Tally all VP at end of game: defeated villains + mastermind hits + rescued bystanders. ' +
      'Highest VP wins (or all heroes win together if the mastermind was defeated).',
  },
];
